### ISSUE TITLE
Format strings support in section args and for shell command

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#122]
- [x] Support highlighting for arguments of format strings #53
- [x] Params completion for shell cmd in run section #102
- [x] 'shell' section: resolve & completion for `params` args #43
- [x] Resolve/Completion for: input, output, params rule options in shell argument #3
- [x] 'shell' section & call: resolve & completion for input args #152
