### ISSUE TITLE
Do not hardcode the list of allows section names in parser

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#334]
Snakemake adds new section names from time to time and this leads to errors like #332. In order to be more friendly to newer snakemake releases parser behavior should be improved.

Parser keeps the list of know section names to differ misspelled identifiers from correct ones. E.g. `output` is ok, `outupt` is wrong. A possible fix is:

- [x] Allow any section in rule, checkpoint, subworkflow
- [x] Allow any section on toplevel, i.e. statement like: `some_identifier: ` (#373)
- [ ] add warning which detects misspelled section names, e.g we could use Levenshtein or etc distance to predict the expected section name + quick fix (#374)
- [x] add weak warning inspection that highlights supported keywords. Users could suppress such warnings or turn of the inspeciton.
- [x] Allow plugin to memorize new section names in order to disable warning for them - e.g. using quickfix + list in plugin settings.  (#372)
- [ ] A warning that warns if some section name couldn't be used with project snakemake version (from settings) (#375)
- [ ] Add the ability to configure new section (e.g. via YAML file, which specifies can we use wildcards with this file and so on) (#382 )

**Comment by iromeo** [comment]
Majority of features fixed, let's close this issue and left minor issues.
