### ISSUE TITLE
Resolve/completion code insight for rules

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#6]
Subtasks
 - [x] Resolve/completion for rules names #59
 - [x] Completion / Resolve for rules name in 'ruleorder' and 'localrules' #56
 - [x] Resolve/Completion after `rules.some_rule_name.` #55 
 - [x] Find usages doesn't work for rules/checkpoints #100

**Comment by iromeo** [comment]
Also in subworkflows

```
subworkflow otherworkflow:
    workdir:
        "../path/to/otherworkflow"
    snakefile:
        "../path/to/otherworkflow/Snakefile"
    configfile:
        "path/to/custom_configfile.yaml"

rule a:
    input:
        otherworkflow("test.txt")
    output: ...
    shell:  ...
```

**Comment by iromeo** [comment]
Early prototype:

![2019-05-11_18-20-08](https://user-images.githubusercontent.com/72933/57572627-b4f3cf80-7425-11e9-9d30-977d6b03b7dc.png)

![2019-05-11_18-18-18](https://user-images.githubusercontent.com/72933/57572630-b8875680-7425-11e9-8ea0-712f759d745b.png)

**Comment by iromeo** [comment]
obsolete
