### ISSUE TITLE
Subworkflows support

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/snakecharm#90]
- [x] Subworkflow parsing errors #66
- [x] Code completion for subworkflow sections names #11
- [x] Subworflow redeclaration inspection #88
- [x] Inspection: subworkflow 'workdir', 'snakefile', 'configfile' could accept only single arg #83 
- [x] Resolve/Completion for subworflows names #60
